app:
  cors:
    allowed-origins: "http://localhost:3000"
security:
  jwt:
    secret: ${JWT_SECRET:e+WLevA5+p/vKqKx6b1t0Vde0SG+eOm0NPv3/Hy0xBk=}
    issuer: bankcards
    expiry-minutes: 60

crypto:
  aes-key: ${CRYPTO_AES_KEY:Ckrw/gcyrRFrTxU2nDxlMlVyX/Ox3q2mDM6HsEEPxgM=}
  hmac-key: ${CRYPTO_HMAC_KEY:78q6k1VRx2jysPU6l0ML0Ea/bYbzNfmJO5rPre/xN4g=}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: bankcards
    password: bankcards
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
server:
  port: 8080
